#!/bin/bash
set -euo pipefail
shopt -s extglob

backup_file_name=virtual.tar.gz
stash_file_name=virtual_stash
dotgit=$(git rev-parse --show-toplevel)/.git
backup_file=$dotgit/$backup_file_name
stash_file=$dotgit/$stash_file_name

: "check the .git/$backup_file_name existance"
if [[ ! -e $backup_file ]]; then
  echo "the backup file '.git/$backup_file_name' does not exist" 1>&2
  exit 1
fi

: "restore the git state from the backup file"
rm -rf $dotgit/!(objects|$backup_file_name)
tar xzf $backup_file -C $dotgit
rm $backup_file
git reset --hard HEAD >/dev/null
git clean -f >/dev/null

if [[ -e $stash_file ]]; then
  git stash apply $(cat $stash_file) >/dev/null
  rm $stash_file
fi
