#!/bin/bash
set -euo pipefail

backup_file_name=virtual.tar.gz
stash_file_name=virtual_stash
dotgit=$(git rev-parse --show-toplevel)/.git
backup_file=$dotgit/$backup_file_name
stash_file=$dotgit/$stash_file_name

: "check the .git/$backup_file_name existance"
if [[ -e $backup_file ]]; then
  echo "the backup file '.git/$backup_file_name' already exists" 1>&2
  exit 1
fi

: "backup the current git state to the backup file"
if git stash -u | grep -q 'Saved working directory'; then
  git rev-parse stash > $stash_file
  git stash pop >/dev/null
fi

cd $dotgit
tar czf ./$backup_file_name --exclude ./$backup_file_name --exclude ./objects .
